### ISSUE TITLE
how to verify that deployment was successful ? 

### ISSUE THREAD

**Issue by Ahmad-Al-Ali** [Azure/azure-docs-sdk-java#586] opened 2018-08-27 11:35 UTC
I'm assuming that when I browse the app after deploying to azure, I get the HelloController page but instead I get this message from Azure "This Java based web application has been successfully created
There's nothing here yet"  does that mean that the deployment wasn't successful ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 83f018e3-40db-c279-9bd0-f0de6246a1bc
* Content: [Deploy a Spring Boot app to the cloud with Maven and Azure](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm;kevinzha;brborges**

**Comment by fastcoretux** [comment] 2018-10-17 06:28
It's same here. Yesterday evening I had same result as you, multiple times, but today I can see message from HelloController GET operation.

So it is quite unpredictable.

**Comment by brunoborges** [comment] 2018-10-17 09:49
@JasonFreeberg @jvano: do you have any information about the time it takes between a successful deployment is informed to the user from the Maven plugin and then when the app is actually up and running? 

I feel that we should be showing a page like "Your app is starting" instead of the "This Java based web application has been successfully created. There's nothing here yet"

// @selvasingh

**Comment by samseth** [comment] 2018-10-24 17:21
I see following error when I try to deploy using: mvn azure-webapp:deploy
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project gs-spring-boot: The zip deploy failed after 3 times of retry.

**Comment by jvano** [comment] 2018-10-24 18:54
The issue is that ZipDeploy is not deleting the content as WarDeploy does. We have a bug to fix this issue. Basically, just go to Kudu or FTP to the site and remove the .jsp file that we copy to the site's storage when the site gets created.

**Comment by rmcmurray** [comment] 2019-09-25 06:50
This has been fixed in #929

**Closed by rmcmurray** 2019-09-25 06:50 UTC
Labels: app-service
